- name: Demo o loops
  hosts: localhost
  vars:
    FRUITS: [ "apple" , "banana" , "orange" ]
  tasks:
   - name: print all fruits
     debug:
      msg: :fruit name = {{item}}
     loop: "{{FRUITS}}"

- name: Demo on map values of loop
  hosts: localhost
  tasks:
   - name: Print
     debug:
      msg: " Course name = {[item.name]}, timing = {{item.timing}}
     loop:
      - name: devops
        timing: 6am
      - name: AWS
        timing: 8am

