- name: Install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes


